name: weekly_scraper

on:
  # workflow_dispatch
  schedule:
    - cron: '25 7 * * 3' # At 7:25am on Wednesday

jobs:
  scrape-legal-acts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup_ruby
        uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          ruby-version: 3.0
          bundler-cache: 'true'
          cache-version: '6'

      - name: run_scraper
        run: bundle exec ruby scraper.rb

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "Robot Scraper"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add gesetze/*
          git commit -m 'Scraping of legal acts'
          git push origin main
